In [13]:
import pandas as pd

# Load the dataset
file_path = r'E:\Case Study 2 data from case study (1).xlsx'
sheet_name = 'Sample_Data_on_Past_Sales_Leads'
df = pd.read_excel(file_path, sheet_name)

# Count of products under each Lead Conversion Class
class_counts = df['Leads_Conversion_Class'].value_counts()

# Display count of products under each class
print("\n\033[1mLead Conversion Class Counts: \033[0m")
print(class_counts)

# Create a pivot table to show which product is sold in which region and its reporting status
pivot_table = pd.pivot_table(df, values='Product', index=['Region', 'Reporting_Status'], columns='Leads_Conversion_Class', aggfunc='count', fill_value=0)

# Display the pivot table
print("\n\033[1mProduct Distribution Across Regions and Reporting Status: \033[0m")
print(pivot_table)

Lead Conversion Class Counts:
V    398
E    390
L    142
F     70
Name: Leads_Conversion_Class, dtype: int64

Product Distribution Across Regions and Reporting Status:
Leads_Conversion_Class           E   F   L    V
Region       Reporting_Status
Africa       Lost               16   3   3   16
             Won                25   2   7   21
Americas     Lost               15   7  10   17
             Won                21   1  14   19
Canada       Lost                1   0   1    0
             Won                 1   0   0    3
India        Lost                9   0   3    6
             Won                 8   0   2    7
Japan        Lost                4   0   0    2
             Won                 3   1   3    3
Other Europe Lost               27  12  14   39
             Won                25   4   3   34
Singapore    Lost                9   0   2    6
             Won                 1   0   2    3
Spain        Lost                6   1   1    3
             Won                 1   0   0    0
UK           Lost              113  27  35  111
             Won               105  12  42  108

In [14]:
import pandas as pd

# Load the dataset
file_path = r'E:\Case Study 2 data from case study (1).xlsx'
sheet_name = 'Sample_Data_on_Past_Sales_Leads'
df = pd.read_excel(file_path, sheet_name)

# Create a pivot table to show which product is sold in which region and its reporting status
pivot_table = pd.pivot_table(df, values='Product', index=['Region', 'Reporting_Status'], columns='Leads_Conversion_Class', aggfunc='count', fill_value=0)

# Add a row for the total number of deals in each region
pivot_table['Total Deals'] = pivot_table.sum(axis=1)

# Add a column for the total number of deals in each Lead Conversion Class
pivot_table.loc['Total Deals'] = pivot_table.sum()

# Display the pivot table
print("\nProduct Distribution Across Regions and Reporting Status:")
print(pivot_table)

Product Distribution Across Regions and Reporting Status:
Leads_Conversion_Class    E   F    L    V  Total Deals
(Africa, Lost)           16   3    3   16           38
(Africa, Won)            25   2    7   21           55
(Americas, Lost)         15   7   10   17           49
(Americas, Won)          21   1   14   19           55
(Canada, Lost)            1   0    1    0            2
(Canada, Won)             1   0    0    3            4
(India, Lost)             9   0    3    6           18
(India, Won)              8   0    2    7           17
(Japan, Lost)             4   0    0    2            6
(Japan, Won)              3   1    3    3           10
(Other Europe, Lost)     27  12   14   39           92
(Other Europe, Won)      25   4    3   34           66
(Singapore, Lost)         9   0    2    6           17
(Singapore, Won)          1   0    2    3            6
(Spain, Lost)             6   1    1    3           11
(Spain, Won)              1   0    0    0            1
(UK, Lost)              113  27   35  111          286
(UK, Won)               105  12   42  108          267
Total Deals             390  70  142  398         1000

In [17]:
import pandas as pd

# Load the dataset
file_path = r'E:\Case Study 2 data from case study (1).xlsx'
sheet_name = 'Sample_Data_on_Past_Sales_Leads'
df = pd.read_excel(file_path, sheet_name)

# Create a pivot table to show the distribution of products with Lead Conversion Class, Industry, Region, Relative Strength, and WSES Joint Bid
pivot_table = pd.pivot_table(df, values=['Product'], index=['Leads_Conversion_Class', 'Industry', 'Region', 'Relative_Strength_in_the_segment', 'WSES_Proportion_in_Joint_Bid'], aggfunc='count', fill_value=0)

# Display the pivot table
print("\nProduct Distribution by Lead Conversion Class, Industry, Region, Relative Strength, and WSES Joint Bid:")
print(pivot_table)

Product Distribution by Lead Conversion Class, Industry, Region, Relative Strength, and WSES Joint Bid:
                                                                                                                      Product
Leads_Conversion_Class Industry           Region       Relative_Strength_in_the_segment WSES_Proportion_in_Joint_Bid
E                      Agriculture        Other Europe 26                               61                                  1
                       Airline            UK           56                               41                                  1
                                                                                        49                                  2
                                                                                        50                                  1
                                                                                        53                                  1
...                                                                                                                       ...
V                      Security           UK           76                               56                                  1
                                                                                        61                                  1
                       Telecom equipments Spain        66                               47                                  1
                                                                                        57                                  1
                                                                                        63                                  1

[879 rows x 1 columns]

In [19]:
import pandas as pd

# Load the dataset
file_path = r'E:\Case Study 2 data from case study (1).xlsx'
sheet_name = 'Sample_Data_on_Past_Sales_Leads'
df = pd.read_excel(file_path, sheet_name)

# Filter data for 'E' class
e_class_data = df[df['Leads_Conversion_Class'] == 'E']

# Create a pivot table to show the distribution of products with 'E' class
pivot_table_e_class = pd.pivot_table(e_class_data, values=['Product'], index=['Leads_Conversion_Class', 'Industry', 'Region', 'Relative_Strength_in_the_segment', 'WSES_Proportion_in_Joint_Bid'], aggfunc='count', fill_value=0)

# Display the pivot table for 'E' class
print("\nProduct Distribution for 'E' class by Industry, Region, Relative Strength, and WSES Joint Bid:")
print(pivot_table_e_class)

Product Distribution for 'E' class by Industry, Region, Relative Strength, and WSES Joint Bid:
                                                                                                                      Product
Leads_Conversion_Class Industry           Region       Relative_Strength_in_the_segment WSES_Proportion_in_Joint_Bid
E                      Agriculture        Other Europe 26                               61                                  1
                       Airline            UK           56                               41                                  1
                                                                                        49                                  2
                                                                                        50                                  1
                                                                                        53                                  1
...                                                                                                                       ...
                       Telecom equipments Spain        66                               57                                  1
                                                                                        65                                  1
                                                                                        67                                  1
                                                                                        68                                  2
                                                                                        73                                  1

[336 rows x 1 columns]

In [20]:
import pandas as pd

# Load the dataset
file_path = r'E:\Case Study 2 data from case study (1).xlsx'
sheet_name = 'Sample_Data_on_Past_Sales_Leads'
df = pd.read_excel(file_path, sheet_name)

# Filter data for 'E' class
e_class_data = df[df['Leads_Conversion_Class'] == 'E']

# Create a pivot table to show the distribution of products with 'E' class
pivot_table_e_class = pd.pivot_table(e_class_data, values=['Product'], index=['Leads_Conversion_Class', 'Industry', 'Region', 'Relative_Strength_in_the_segment', 'WSES_Proportion_in_Joint_Bid'], aggfunc='count', fill_value=0)

# Display the pivot table for 'E' class
print("\nProduct Distribution for 'E' class by Industry, Region, Relative Strength, and WSES Joint Bid:")
print(pivot_table_e_class)

Product Distribution for 'E' class by Industry, Region, Relative Strength, and WSES Joint Bid:
                                                                                                                      Product
Leads_Conversion_Class Industry           Region       Relative_Strength_in_the_segment WSES_Proportion_in_Joint_Bid
E                      Agriculture        Other Europe 26                               61                                  1
                       Airline            UK           56                               41                                  1
                                                                                        49                                  2
                                                                                        50                                  1
                                                                                        53                                  1
...                                                                                                                       ...
                       Telecom equipments Spain        66                               57                                  1
                                                                                        65                                  1
                                                                                        67                                  1
                                                                                        68                                  2
                                                                                        73                                  1

[336 rows x 1 columns]

In [26]:
import pandas as pd

# Load the dataset
file_path = r'E:\Case Study 2 data from case study (1).xlsx'
sheet_name = 'Sample_Data_on_Past_Sales_Leads'
df = pd.read_excel(file_path, sheet_name)

# Create a pivot table to show the distribution of products by Region and Lead Conversion Class
pivot_table_products_by_region = pd.pivot_table(df, values=['Product'], index=['Region', 'Leads_Conversion_Class'], aggfunc='count', fill_value=0, margins=True, margins_name='Total')

# Display the pivot table with totals for each region and won deals for each class in each region
print("\nProduct Distribution by Region and Lead Conversion Class:")
print(pivot_table_products_by_region)

# Calculate and display the total for each region
total_by_region = pd.pivot_table(df, values=['Product'], index=['Region'], aggfunc='count', fill_value=0)
print("\nTotal for Each Region:")
print(total_by_region)

# Calculate and display the number of won deals for each class in each region
won_deals_by_class = pd.pivot_table(df[df['Reporting_Status'] == 'Won'], values=['Product'], index=['Region', 'Leads_Conversion_Class'], aggfunc='count', fill_value=0, margins=True, margins_name='Total')
print("\nNumber of Won Deals by Class in Each Region:")
print(won_deals_by_class)

Product Distribution by Region and Lead Conversion Class:
                                     Product
Region       Leads_Conversion_Class
Africa       E                            41
             F                             5
             L                            10
             V                            37
Americas     E                            36
             F                             8
             L                            24
             V                            36
Canada       E                             2
             L                             1
             V                             3
India        E                            17
             L                             5
             V                            13
Japan        E                             7
             F                             1
             L                             3
             V                             5
Other Europe E                            52
             F                            16
             L                            17
             V                            73
Singapore    E                            10
             L                             4
             V                             9
Spain        E                             7
             F                             1
             L                             1
             V                             3
UK           E                           218
             F                            39
             L                            77
             V                           219
Total                                   1000

Total for Each Region:
              Product
Region
Africa             93
Americas          104
Canada              6
India              35
Japan              16
Other Europe      158
Singapore          23
Spain              12
UK                553

Number of Won Deals by Class in Each Region:
                                     Product
Region       Leads_Conversion_Class
Africa       E                            25
             F                             2
             L                             7
             V                            21
Americas     E                            21
             F                             1
             L                            14
             V                            19
Canada       E                             1
             V                             3
India        E                             8
             L                             2
             V                             7
Japan        E                             3
             F                             1
             L                             3
             V                             3
Other Europe E                            25
             F                             4
             L                             3
             V                            34
Singapore    E                             1
             L                             2
             V                             3
Spain        E                             1
UK           E                           105
             F                            12
             L                            42
             V                           108
Total                                    481

In [31]:
import pandas as pd

# Load the dataset
file_path = r'E:\Case Study 2 data from case study (1).xlsx'
sheet_name = 'Sample_Data_on_Past_Sales_Leads'
df = pd.read_excel(file_path, sheet_name)

# Create a pivot table to show the distribution of products by Industry and Lead Conversion Class
pivot_table_products_by_industry = pd.pivot_table(df, values=['Product'], index=['Industry', 'Leads_Conversion_Class'], columns=['Reporting_Status'], aggfunc='count', fill_value=0, margins=True, margins_name='Total')

# Display the pivot table with totals for each industry and won/lost deals for each class in each industry
print("\nProduct Distribution by Industry, Lead Conversion Class, and Reporting Status:")
print(pivot_table_products_by_industry)

# Calculate and display the total for each industry
total_by_industry = pd.pivot_table(df, values=['Product'], index=['Industry'], columns=['Reporting_Status'], aggfunc='count', fill_value=0, margins=True, margins_name='Total')
print("\nTotal for Each Industry:")
print(total_by_industry)

# Calculate and display the number of won deals for each class in each industry
won_deals_by_class_industry = pd.pivot_table(df[df['Reporting_Status'] == 'Won'], values=['Product'], index=['Industry', 'Leads_Conversion_Class'], aggfunc='count', fill_value=0, margins=True, margins_name='Total')
print("\nNumber of Won Deals by Class in Each Industry:")
print(won_deals_by_class_industry)

Product Distribution by Industry, Lead Conversion Class, and Reporting Status:
                                          Product
Reporting_Status                             Lost  Won Total
Industry           Leads_Conversion_Class
Agriculture        E                            0    1     1
                   V                            1    0     1
Airline            E                            5    8    13
                   F                            4    0     4
                   L                            3    2     5
...                                           ...  ...   ...
Telecom equipments E                            6    1     7
                   F                            1    0     1
                   L                            1    0     1
                   V                            3    0     3
Total                                         519  481  1000

[64 rows x 3 columns]

Total for Each Industry:
                   Product
Reporting_Status      Lost  Won Total
Industry
Agriculture              1    1     2
Airline                 22   12    34
Banks                   89   72   161
Capital Markets        105   98   203
Clinical research        6    1     7
Consumer goods          63   52   115
Defense                 47   50    97
Energy                  22   26    48
Finance                 16   17    33
Govt.                    6    8    14
Health                   4    1     5
Infrastructure          16   10    26
Insurance               21   18    39
Mobility                 3   16    19
Other Govt.              2    8    10
Others                  56   58   114
Security                29   32    61
Telecom equipments      11    1    12
Total                  519  481  1000

Number of Won Deals by Class in Each Industry:
                                           Product
Industry           Leads_Conversion_Class
Agriculture        E                             1
Airline            E                             8
                   L                             2
                   V                             2
Banks              E                            30
                   F                             4
                   L                            11
                   V                            27
Capital Markets    E                            37
                   F                             3
                   L                             9
                   V                            49
Clinical research  L                             1
Consumer goods     E                            18
                   F                             3
                   L                            10
                   V                            21
Defense            E                            27
                   F                             1
                   L                             4
                   V                            18
Energy             E                             7
                   F                             2
                   L                             4
                   V                            13
Finance            E                             7
                   L                             3
                   V                             7
Govt.              E                             2
                   L                             2
                   V                             4
Health             E                             1
Infrastructure     E                             5
                   F                             1
                   L                             1
                   V                             3
Insurance          E                             9
                   F                             2
                   L                             3
                   V                             4
Mobility           E                             5
                   L                             3
                   V                             8
Other Govt.        E                             2
                   L                             3
                   V                             3
Others             E                            17
                   F                             4
                   L                            14
                   V                            23
Security           E                            13
                   L                             3
                   V                            16
Telecom equipments E                             1
Total                                          481

In [33]:
def find_max_min(lst):
    if not lst:
        return None, None  # Return None for both max and min if the list is empty
    else:
        return max(lst), min(lst)

# Example usage:
my_list = [45,25,52,52,39,52,52,39,39,52,45,45,45,45,39,52,39,45,52,52,45,52,52,52,45,45,39,52,52,52,52,45,52,39,45,52,45,39,45,25,45,52,52,52,52,45,39,52,45,52,39,52,45,39,25,45,45,52,45,45,52,52,39,25,39,52,45,45,52,45,39,52,39,25,45,52,45,45,52,39,52,52,39,39,45,52,39,45,45,52,52,52,45]
maximum, minimum = find_max_min(my_list)

print("Maximum value:", maximum)
print("Minimum value:", minimum)

Maximum value: 52
Minimum value: 25