In [1]:
import pandas as pd
df=pd.read_csv(r"E:\Portfolio\AirBnB\Unzip\full_listings.csv\listings.csv")
df.head(10)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,198258,https://www.airbnb.com/rooms/198258,2.023120e+13,10-12-2023,city scrape,Rental unit in Barking · ★4.74 · 1 bedroom · 1...,NaN,"I live in Barking town centre, at one time the...",https://a0.muscache.com/pictures/airflow/Hosti...,967537,...,4.88,4.45,4.68,NaN,f,1,0,1,0,0.27
1,33332,https://www.airbnb.com/rooms/33332,2.023120e+13,10-12-2023,city scrape,"Home in St Margaret's, Isleworth · ★4.40 · 1 ...",NaN,Peaceful and friendly.,https://a0.muscache.com/pictures/miso/Hosting-...,144444,...,4.53,4.68,4.26,NaN,f,2,0,2,0,0.12
2,42010,https://www.airbnb.com/rooms/42010,2.023120e+13,10-12-2023,city scrape,Home in East Finchley · ★4.88 · 1 bedroom · 1 ...,NaN,We have a unique cinema called the Phoenix whi...,https://a0.muscache.com/pictures/airflow/Hosti...,157884,...,4.95,4.73,4.87,NaN,t,2,0,2,0,3.45
3,284603,https://www.airbnb.com/rooms/284603,2.023120e+13,11-12-2023,previous scrape,Rental unit in London · ★4.83 · 1 bedroom · 1 ...,NaN,NaN,https://a0.muscache.com/pictures/3246231/8e9b1...,1481851,...,5.00,5.00,4.83,NaN,f,1,1,0,0,0.04
4,89870,https://www.airbnb.com/rooms/89870,2.023120e+13,10-12-2023,city scrape,Rental unit in London · ★4.65 · 1 bedroom · 1 ...,NaN,Finsbury Park is a friendly melting pot commun...,https://a0.muscache.com/pictures/miso/Hosting-...,54730,...,4.91,4.73,4.50,NaN,f,3,2,1,0,0.89
5,326146,https://www.airbnb.com/rooms/326146,2.023120e+13,13-12-2023,previous scrape,Rental unit in London · 1 bedroom · 1 bed,NaN,NaN,https://a0.muscache.com/pictures/3536712/9c7a9...,1667975,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
6,96052,https://www.airbnb.com/rooms/96052,2.023120e+13,10-12-2023,city scrape,Condo in London · ★4.82 · 2 bedrooms · 1 bed ·...,NaN,"Residential, quiet and green neighbourhood wit...",https://a0.muscache.com/pictures/airflow/Hosti...,448154,...,4.90,4.45,4.70,NaN,f,2,0,2,0,0.52
7,381467,https://www.airbnb.com/rooms/381467,2.023120e+13,11-12-2023,previous scrape,Rental unit in London · ★4.66 · 2 bedrooms · 2...,NaN,Peaceful and quite with beautiful tree lined s...,https://a0.muscache.com/pictures/4700556/fcce1...,1913410,...,4.82,4.88,4.64,NaN,f,1,1,0,0,1.86
8,390987,https://www.airbnb.com/rooms/390987,2.023120e+13,10-12-2023,city scrape,Home in London · ★4.73 · 8 bedrooms · 1 bed · ...,NaN,The neighbourhood is safe and many new cafes a...,https://a0.muscache.com/pictures/8841768/8130b...,1955537,...,4.83,4.75,4.75,NaN,f,3,0,3,0,0.09
9,394755,https://www.airbnb.com/rooms/394755,2.023120e+13,11-12-2023,previous scrape,Rental unit in London · 2 bedrooms · 2 beds · ...,NaN,NaN,https://a0.muscache.com/pictures/2b043814-44d7...,1973515,...,5.00,5.00,4.00,NaN,f,1,1,0,0,0.01

<span style="color:blue">Loading the dataset</span>

In [2]:
df.shape

(91778, 75)

In [3]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [4]:
x=df.columns[df.isnull().all()].tolist()
x

['description',
 'neighbourhood_group_cleansed',
 'bathrooms',
 'calendar_updated',
 'license']

In [9]:
df.drop(['description',
 'neighbourhood_group_cleansed',
 'bathrooms',
 'calendar_updated',
 'license'], axis=1, inplace=True)

<span style="color:blue">Dropping columns which are completely null </span>

In [10]:
numeric=df.select_dtypes(['int64', 'float64']).columns.tolist()
numeric

['id',
 'scrape_id',
 'host_id',
 'host_listings_count',
 'host_total_listings_count',
 'latitude',
 'longitude',
 'accommodates',
 'bedrooms',
 'beds',
 'minimum_nights',
 'maximum_nights',
 'minimum_minimum_nights',
 'maximum_minimum_nights',
 'minimum_maximum_nights',
 'maximum_maximum_nights',
 'minimum_nights_avg_ntm',
 'maximum_nights_avg_ntm',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'number_of_reviews',
 'number_of_reviews_ltm',
 'number_of_reviews_l30d',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'calculated_host_listings_count',
 'calculated_host_listings_count_entire_homes',
 'calculated_host_listings_count_private_rooms',
 'calculated_host_listings_count_shared_rooms',
 'reviews_per_month']

<span style="color:blue">Identifying the numeric columns</span>

In [7]:
cols=['host_listings_count','host_total_listings_count','bedrooms', 'beds',
      'minimum_minimum_nights','maximum_minimum_nights','minimum_maximum_nights', 'maximum_maximum_nights',
      'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 
      'review_scores_rating','review_scores_accuracy', 'review_scores_cleanliness','review_scores_checkin',                           
      'review_scores_communication', 'review_scores_location', 'review_scores_value','reviews_per_month']

for column in cols:
    if column in df.columns:
        df[column].fillna(df[column].mean(), inplace=True)

<span style="color:blue">Filling the null entries with mean value</span>

In [12]:
df[numeric].isnull().sum()

id                                              0
scrape_id                                       0
host_id                                         0
host_listings_count                             0
host_total_listings_count                       0
latitude                                        0
longitude                                       0
accommodates                                    0
bedrooms                                        0
beds                                            0
minimum_nights                                  0
maximum_nights                                  0
minimum_minimum_nights                          0
maximum_minimum_nights                          0
minimum_maximum_nights                          0
maximum_maximum_nights                          0
minimum_nights_avg_ntm                          0
maximum_nights_avg_ntm                          0
availability_30                                 0
availability_60                                 0
availability_90                                 0
availability_365                                0
number_of_reviews                               0
number_of_reviews_ltm                           0
number_of_reviews_l30d                          0
review_scores_rating                            0
review_scores_accuracy                          0
review_scores_cleanliness                       0
review_scores_checkin                           0
review_scores_communication                     0
review_scores_location                          0
review_scores_value                             0
calculated_host_listings_count                  0
calculated_host_listings_count_entire_homes     0
calculated_host_listings_count_private_rooms    0
calculated_host_listings_count_shared_rooms     0
reviews_per_month                               0
dtype: int64

In [13]:
y=df.columns[df.isnull().any()].tolist()
y

['neighborhood_overview',
 'picture_url',
 'host_name',
 'host_since',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_acceptance_rate',
 'host_is_superhost',
 'host_thumbnail_url',
 'host_picture_url',
 'host_neighbourhood',
 'host_has_profile_pic',
 'host_identity_verified',
 'neighbourhood',
 'bathrooms_text',
 'price',
 'has_availability',
 'first_review',
 'last_review']

<span style="color:blue">Finding the other(non-integers) null columns</span>

In [14]:
COLUMNS=['neighborhood_overview','picture_url','host_name','host_since',
         'host_location','host_about','host_response_time','host_response_rate',
         'host_acceptance_rate','host_is_superhost','host_thumbnail_url','host_picture_url',
         'host_neighbourhood','host_has_profile_pic','host_identity_verified',
         'neighbourhood','bathrooms_text','price','has_availability','first_review','last_review']

subset=df[COLUMNS]
subset.head(10)

,neighborhood_overview,picture_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,...,host_picture_url,host_neighbourhood,host_has_profile_pic,host_identity_verified,neighbourhood,bathrooms_text,price,has_availability,first_review,last_review
0,"I live in Barking town centre, at one time the...",https://a0.muscache.com/pictures/airflow/Hosti...,Ryan,14-08-2011,"Barking, United Kingdom","Do the Math\r\n\r\nHi all, im just a crazy kid...",within an hour,100%,75%,f,...,https://a0.muscache.com/im/pictures/user/360a7...,NaN,t,t,"Barking, London, United Kingdom",1 shared bath,$67.00,t,22-08-2011,16-03-2023
1,Peaceful and friendly.,https://a0.muscache.com/pictures/miso/Hosting-...,Chi-Chi,14-06-2010,"Isleworth, United Kingdom",Quite busy and often in a different place ever...,NaN,NaN,NaN,f,...,https://a0.muscache.com/im/pictures/user/8028d...,LB of Hounslow,t,f,"St Margaret's, Isleworth, Middlesex, United K...",1 private bath,$140.00,t,16-10-2010,01-08-2022
2,We have a unique cinema called the Phoenix whi...,https://a0.muscache.com/pictures/airflow/Hosti...,Agri & Roger,04-07-2010,"London, United Kingdom",We are a happy couple who live in a wonderful ...,within a few hours,100%,100%,t,...,https://a0.muscache.com/im/users/157884/profil...,LB of Haringey,t,t,"East Finchley, United Kingdom",1 shared bath,$65.00,t,22-09-2010,03-12-2023
3,NaN,https://a0.muscache.com/pictures/3246231/8e9b1...,Tania,07-12-2011,"London, United Kingdom",Hello! Thank you for visiting my place! \r\n\r...,NaN,NaN,100%,f,...,https://a0.muscache.com/im/users/1481851/profi...,Westbourne Green,t,t,NaN,1.5 baths,$297.00,f,16-07-2012,04-07-2022
4,Finsbury Park is a friendly melting pot commun...,https://a0.muscache.com/pictures/miso/Hosting-...,Alina,16-11-2009,"London, United Kingdom",I am a Multi-Media Visual Artist and Creative ...,within an hour,90%,85%,f,...,https://a0.muscache.com/im/users/54730/profile...,LB of Islington,t,t,"London, United Kingdom",1 bath,$149.00,t,14-08-2011,03-12-2023
5,NaN,https://a0.muscache.com/pictures/3536712/9c7a9...,Inma,29-01-2012,"London, United Kingdom","Hi my name is Inma ,\r\n\r\nI am a native Spa...",NaN,NaN,NaN,f,...,https://a0.muscache.com/im/pictures/user/11b86...,NaN,t,f,NaN,NaN,$120.00,f,NaN,NaN
6,"Residential, quiet and green neighbourhood wit...",https://a0.muscache.com/pictures/airflow/Hosti...,Aneta,17-03-2011,"London, United Kingdom",I also love to travel myself and look forward ...,within a few hours,100%,90%,t,...,https://a0.muscache.com/im/pictures/user/182ee...,LB of Brent,t,t,"London, England, United Kingdom",1 shared bath,$52.00,t,24-05-2011,24-11-2023
7,Peaceful and quite with beautiful tree lined s...,https://a0.muscache.com/pictures/4700556/fcce1...,Thanos,13-03-2012,"London, United Kingdom",Professional and friendly guy welcomes you to ...,NaN,NaN,NaN,f,...,https://a0.muscache.com/im/users/1913410/profi...,Earls Court,t,t,"London, United Kingdom",1.5 baths,$143.00,f,03-04-2012,20-07-2018
8,The neighbourhood is safe and many new cafes a...,https://a0.muscache.com/pictures/8841768/8130b...,Ali,18-03-2012,"London, United Kingdom","Easy going, socialable, always on the go! Enjo...",within a few hours,100%,88%,t,...,https://a0.muscache.com/im/users/1955537/profi...,West Norwood,t,t,"London, United Kingdom",1 shared bath,$41.00,t,15-05-2013,11-07-2023
9,NaN,https://a0.muscache.com/pictures/2b043814-44d7...,Lara,20-03-2012,"London, United Kingdom",I am studying Osteopathy at BCOM in Finchley R...,NaN,NaN,NaN,f,...,https://a0.muscache.com/im/pictures/user/914e5...,LB of Camden,t,f,NaN,1.5 baths,$80.00,f,05-08-2016,05-08-2016

<span style="color:blue">Viewing all categorical columns as a dataframe</span>

In [15]:
COLUMNS=['neighborhood_overview','picture_url','host_name','host_since',
         'host_location','host_about','host_response_time','host_response_rate',
         'host_acceptance_rate','host_is_superhost','host_thumbnail_url','host_picture_url',
         'host_neighbourhood','host_has_profile_pic','host_identity_verified',
         'neighbourhood','bathrooms_text','price','has_availability','first_review','last_review']
for column in COLUMNS:
    df[column].fillna(method='ffill', inplace=True)

<span style="color:blue">Forward Filling all the NaN values in the categorical columns</span>

In [16]:
y=df.columns[df.isnull().any()].tolist()
y

['host_neighbourhood']

In [17]:
df['host_neighbourhood'].fillna(method='bfill', inplace=True)

<span style="color:blue">Using backward fill for columns 'host_neighbourhood'</span>

In [18]:
y=df.columns[df.isnull().any()].tolist()
y

[]

<span style="color:blue">No column is null now</span>

In [ ]:
df.drop(['picture_url'], axis=1, inplace=True)

In [19]:
ROUND=['bedrooms', 'beds', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'reviews_per_month'
]

def round_element(x):
    return round(x,2)

df[ROUND]=df[ROUND].applymap(round_element)
df[ROUND]

,bedrooms,beds,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
0,4.16,1.0,4.74,4.83,4.25,4.80,4.88,4.45,4.68,0.27
1,4.16,1.0,4.40,4.47,4.58,4.58,4.53,4.68,4.26,0.12
2,4.16,1.0,4.88,4.89,4.83,4.96,4.95,4.73,4.87,3.45
3,4.16,1.0,4.83,4.83,5.00,5.00,5.00,5.00,4.83,0.04
4,4.16,1.0,4.65,4.68,4.64,4.90,4.91,4.73,4.50,0.89
...,...,...,...,...,...,...,...,...,...,...
91773,4.16,2.0,4.67,4.72,4.63,4.78,4.80,4.72,4.60,1.01
91774,4.16,3.0,3.00,3.00,3.00,4.00,4.00,4.00,3.00,0.57
91775,4.16,4.0,5.00,5.00,5.00,5.00,5.00,5.00,5.00,0.70
91776,4.16,1.0,4.67,4.72,4.63,4.78,4.80,4.72,4.60,1.01
91777,4.16,2.0,3.89,4.56,3.78,4.44,4.33,4.56,3.89,2.73

In [20]:
df

,id,listing_url,scrape_id,last_scraped,source,name,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,198258,https://www.airbnb.com/rooms/198258,2.023120e+13,10-12-2023,city scrape,Rental unit in Barking · ★4.74 · 1 bedroom · 1...,"I live in Barking town centre, at one time the...",https://a0.muscache.com/pictures/airflow/Hosti...,967537,https://www.airbnb.com/users/show/967537,...,4.80,4.88,4.45,4.68,f,1,0,1,0,0.27
1,33332,https://www.airbnb.com/rooms/33332,2.023120e+13,10-12-2023,city scrape,"Home in St Margaret's, Isleworth · ★4.40 · 1 ...",Peaceful and friendly.,https://a0.muscache.com/pictures/miso/Hosting-...,144444,https://www.airbnb.com/users/show/144444,...,4.58,4.53,4.68,4.26,f,2,0,2,0,0.12
2,42010,https://www.airbnb.com/rooms/42010,2.023120e+13,10-12-2023,city scrape,Home in East Finchley · ★4.88 · 1 bedroom · 1 ...,We have a unique cinema called the Phoenix whi...,https://a0.muscache.com/pictures/airflow/Hosti...,157884,https://www.airbnb.com/users/show/157884,...,4.96,4.95,4.73,4.87,t,2,0,2,0,3.45
3,284603,https://www.airbnb.com/rooms/284603,2.023120e+13,11-12-2023,previous scrape,Rental unit in London · ★4.83 · 1 bedroom · 1 ...,We have a unique cinema called the Phoenix whi...,https://a0.muscache.com/pictures/3246231/8e9b1...,1481851,https://www.airbnb.com/users/show/1481851,...,5.00,5.00,5.00,4.83,f,1,1,0,0,0.04
4,89870,https://www.airbnb.com/rooms/89870,2.023120e+13,10-12-2023,city scrape,Rental unit in London · ★4.65 · 1 bedroom · 1 ...,Finsbury Park is a friendly melting pot commun...,https://a0.muscache.com/pictures/miso/Hosting-...,54730,https://www.airbnb.com/users/show/54730,...,4.90,4.91,4.73,4.50,f,3,2,1,0,0.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91773,950589815013504257,https://www.airbnb.com/rooms/950589815013504257,2.023120e+13,11-12-2023,city scrape,Rental unit in Greater London · 2 bedrooms · 2...,"Located at the center of London, Chelsea is wh...",https://a0.muscache.com/pictures/miso/Hosting-...,501508071,https://www.airbnb.com/users/show/501508071,...,4.78,4.80,4.72,4.60,f,31,31,0,0,1.01
91774,951178246905249947,https://www.airbnb.com/rooms/951178246905249947,2.023120e+13,10-12-2023,city scrape,Rental unit in Greater London · 3 bedrooms · 3...,"Located at the center of London, Chelsea is wh...",https://a0.muscache.com/pictures/miso/Hosting-...,211074697,https://www.airbnb.com/users/show/211074697,...,4.00,4.00,4.00,3.00,t,7,7,0,0,0.57
91775,951188392382129035,https://www.airbnb.com/rooms/951188392382129035,2.023120e+13,11-12-2023,city scrape,Home in Greater London · 4 bedrooms · 4 beds ·...,"Located at the center of London, Chelsea is wh...",https://a0.muscache.com/pictures/b4758d11-e7dd...,526113148,https://www.airbnb.com/users/show/526113148,...,5.00,5.00,5.00,5.00,f,2,2,0,0,0.70
91776,951192793768996976,https://www.airbnb.com/rooms/951192793768996976,2.023120e+13,10-12-2023,city scrape,Rental unit in Greater London · 1 bedroom · 1 ...,"Located at the center of London, Chelsea is wh...",https://a0.muscache.com/pictures/miso/Hosting-...,56125082,https://www.airbnb.com/users/show/56125082,...,4.78,4.80,4.72,4.60,f,1,0,1,0,1.01
91777,952607914901368427,https://www.airbnb.com/rooms/952607914901368427,2.023120e+13,10-12-2023,city scrape,Condo in Greater London · ★3.89 · 1 bedroom · ...,"Located at the center of London, Chelsea is wh...",https://a0.muscache.com/pictures/8db8130e-9f93...,513281832,https://www.airbnb.com/users/show/513281832,...,4.44,4.33,4.56,3.89,t,6,6,0,0,2.73

In [22]:
df.to_csv(r"E:\Portfolio\AirBnB\Unzip\full_listings.csv\Cleaned.csv", index=False)

<span style="color:blue">Exporting the results to CSV file</span>

In [26]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'neighborhood_overview', 'picture_url', 'host_id', 'host_url',
       'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'latitude', 'longitude', 'property_type',
       'room_type', 'accommodates', 'bathrooms_text', 'bedrooms', 'beds',
       'amenities', 'price', 'minimum_nights', 'maximum_nights',
       'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')